package com.qik.qa.enums;

public enum ConfigProperties {
    DEVICE_NAME,
    AUTOMATION_NAME,
    SKIPPEDSTEPSCREENSHOTS,
    OVERRIDEREPORTS,
    FAILEDSTEPSCREENSHOTS,
    PASSEDSTEPSCREENSHOTS,
    VERSION,
    PLATFORM_NAME,
    APP;

}
